/**
 * Daily Transaction Report Generator
 * Sends PDF report to admin email (Resend verified)
 */

const https = require('https');
const PDFDocument = require('pdfkit');

const config = {
  cloudflareApiToken: process.env.CLOUDFLARE_API_TOKEN,
  cloudflareAccountId: process.env.CLOUDFLARE_ACCOUNT_ID,
  d1DatabaseId: process.env.D1_DATABASE_ID,
  resendApiKey: process.env.RESEND_API_KEY,
  reportEmail: process.env.REPORT_EMAIL,
};

function makeRequest(options, body = null) {
  return new Promise((resolve, reject) => {
    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => (data += chunk));
      res.on('end', () => {
        try { resolve({ status: res.statusCode, data: JSON.parse(data) }); }
        catch (e) { resolve({ status: res.statusCode, data }); }
      });
    });
    req.on('error', reject);
    if (body) req.write(body);
    req.end();
  });
}

async function queryD1(sql, params = []) {
  const options = {
    hostname: 'api.cloudflare.com',
    path: `/client/v4/accounts/${config.cloudflareAccountId}/d1/database/${config.d1DatabaseId}/query`,
    method: 'POST',
    headers: { 'Authorization': `Bearer ${config.cloudflareApiToken}`, 'Content-Type': 'application/json' },
  };
  const response = await makeRequest(options, JSON.stringify({ sql, params }));
  if (response.status !== 200 || !response.data.success) throw new Error('D1 query failed');
  return response.data.result[0].results;
}

async function getAllAccounts() {
  return queryD1('SELECT * FROM accounts WHERE is_active = 1');
}

async function getDailyTransactions() {
  return queryD1(`SELECT * FROM transactions WHERE created_at >= datetime('now', '-1 day') ORDER BY created_at DESC`);
}

function generatePDF(accounts, transactions) {
  return new Promise((resolve) => {
    const chunks = [];
    const doc = new PDFDocument({ margin: 50 });
    
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    
    // Header
    doc.fontSize(20).text('Mini Bank', { align: 'center' });
    doc.fontSize(14).text('Daily Transaction Report', { align: 'center' });
    doc.moveDown();
    doc.fontSize(12).text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });
    doc.moveDown(2);
    
    // Summary
    const totalBalance = accounts.reduce((sum, acc) => sum + (acc.balance || 0), 0);
    doc.fontSize(14).text('Summary', { underline: true });
    doc.fontSize(12);
    doc.text(`Total Accounts: ${accounts.length}`);
    doc.text(`Total Balance: Rs. ${totalBalance}`);
    doc.text(`Transactions Today: ${transactions.length}`);
    doc.moveDown(2);
    
    // All Accounts
    doc.fontSize(14).text('All Accounts:', { underline: true });
    doc.moveDown();
    doc.fontSize(10);
    doc.text('Name'.padEnd(25) + 'Email'.padEnd(30) + 'Balance');
    doc.text('-'.repeat(70));
    accounts.forEach(acc => {
      doc.text(`${acc.name}`.substring(0, 24).padEnd(25) + `${acc.email}`.substring(0, 29).padEnd(30) + `Rs. ${acc.balance || 0}`);
    });
    doc.moveDown(2);
    
    // Transactions
    doc.fontSize(14).text('Today\'s Transactions:', { underline: true });
    doc.moveDown();
    
    if (transactions.length === 0) {
      doc.fontSize(12).text('No transactions today.');
    } else {
      doc.fontSize(9);
      doc.text('Date/Time'.padEnd(20) + 'From'.padEnd(25) + 'To'.padEnd(25) + 'Amount');
      doc.text('-'.repeat(90));
      
      let totalIn = 0, totalOut = 0;
      transactions.forEach(t => {
        const amount = parseFloat(t.amount);
        totalOut += amount; // just sum all as outgoing
        
        const line = `${t.created_at}`.substring(0, 19).padEnd(20) + 
                     `${t.from_email}`.substring(0, 24).padEnd(25) + 
                     `${t.to_email}`.substring(0, 24).padEnd(25) + 
                     `Rs. ${t.amount}`;
        doc.text(line);
      });
      
      doc.moveDown();
      doc.text('-'.repeat(90));
      doc.fontSize(11);
      doc.text(`Total Amount: Rs. ${totalOut}`);
    }
    
    doc.moveDown(2);
    doc.fontSize(10).text('Generated by Mini Bank App', { align: 'center' });
    
    doc.end();
  });
}

async function sendEmail(pdfBuffer) {
  if (!config.resendApiKey || !config.reportEmail) {
    console.log('No Resend key or report email - skipping');
    return;
  }
  
  const pdfBase64 = pdfBuffer.toString('base64');
  
  const res = await makeRequest({
    hostname: 'api.resend.com',
    path: '/emails',
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${config.resendApiKey}`,
      'Content-Type': 'application/json'
    },
  }, JSON.stringify({
    from: 'Mini Bank <onboarding@resend.dev>',
    to: config.reportEmail,
    subject: `Daily Report - ${new Date().toLocaleDateString()}`,
    text: `Hi, attached is your daily transaction report from Mini Bank.`,
    attachments: [
      {
        filename: `report-${new Date().toISOString().split('T')[0]}.pdf`,
        content: pdfBase64
      }
    ]
  }));
  
  if (res.status !== 200) {
    console.log('Email failed:', res.data);
    throw new Error('Email failed');
  }
}

async function main() {
  if (!config.cloudflareApiToken || !config.cloudflareAccountId || !config.d1DatabaseId) {
    console.log('Missing Cloudflare config - skipping');
    return;
  }
  
  console.log('Generating reports...');
  try {
    const accounts = await getAllAccounts();
    const transactions = await getDailyTransactions();
    
    console.log(`Found ${accounts.length} accounts, ${transactions.length} transactions`);
    
    const pdf = await generatePDF(accounts, transactions);
    await sendEmail(pdf);
    console.log(`Sent PDF to ${config.reportEmail}`);
  } catch (e) {
    console.log('Error:', e.message);
  }
  console.log('Done!');
}

main().catch(e => { console.error(e); process.exit(1); });